version: 2

templates:
  base: &base
    docker:
      # image built from github.com/JulienBalestra/metrics/.circleci/Dockerfile, the tag represent the timestamp
      # when the following command has been run:
      # docker build ${GOPATH}/JulienBalestra/metrics/.circleci/Dockerfile -t julienbalestra/metrics:$(date +%s)
      # docker push !$
      # -> go get binaries like golint/goimports : go mod files are updated
    - image: julienbalestra/metrics:1587406751

jobs:
  fmt:
    <<: *base
    steps:
    - checkout
    - run: make verify-fmt

  import:
    <<: *base
    steps:
    - checkout
    - run: make verify-import

  vet:
    <<: *base
    steps:
    - checkout
    - run: make vet

  lint:
    <<: *base
    steps:
    - checkout
    - run: make lint

  test:
    <<: *base
    steps:
    - checkout
    - run: make test

  build-amd64:
    <<: *base
    steps:
    - checkout
    - run: make amd64

  example:
    <<: *base
    steps:
    - checkout
    - run: go build -o /dev/null pkg/datadog/example/example.go

workflows:
  version: 2
  workflow:
    jobs:
    - fmt
    - import
    - vet
    - lint
    - test
    - build-amd64
    - example
