version: 2

templates:
  base: &base
    docker:
      # TS=$(date +%s)
      # docker build ${GOPATH}/src/github.com/JulienBalestra/monitoring/.circleci/ -t julienbalestra/monitoring:${TS}
      # docker push julienbalestra/monitoring:${TS}
    - image: julienbalestra/monitoring:1588964514

jobs:
  fmt:
    <<: *base
    steps:
    - checkout
    - run: make verify-fmt

  import:
    <<: *base
    steps:
    - checkout
    - run: make verify-import

  vet:
    <<: *base
    steps:
    - checkout
    - run: make vet

  lint:
    <<: *base
    steps:
    - checkout
    - run: make lint

  test:
    <<: *base
    steps:
    - checkout
    - run: make test

  ineffassign:
    <<: *base
    steps:
    - checkout
    - run: make ineffassign

  build-amd64:
    <<: *base
    steps:
    - checkout
    - run: make amd64

  example:
    <<: *base
    steps:
    - checkout
    - run: go build -o /dev/null pkg/datadog/example/example.go

workflows:
  version: 2
  workflow:
    jobs:
    - fmt
    - import
    - vet
    - lint
    - test
    - ineffassign
    - build-amd64
    - example
