collectors:
  - name: datadog-client
    interval: 2m0s
    options: {}
  - name: dnsmasq-dhcp
    interval: 30s
    options:
      leases-file: /tmp/dnsmasq.leases
  - name: dnsmasq-log
    interval: 10s
    options:
      log-facility: /tmp/dnsmasq.log
  - name: dnsmasq-queries
    interval: 30s
    options:
      address: 127.0.0.1:53
  - name: load
    interval: 30s
    options: {}
  - name: memory
    interval: 1m0s
    options:
      meminfo-file: /proc/meminfo
  - name: network-arp
    interval: 10s
    options:
      arp-file: /proc/self/net/arp
  - name: network-conntrack
    interval: 10s
    options:
      conntrack-file: /proc/net/ip_conntrack
  - name: network-statistics
    interval: 10s
    options:
      device-path: /sys/class/net/
  - name: network-wireless
    interval: 10s
    options:
      proc-net-wireless-path: /proc/net/wireless
      sys-class-net-path: /sys/class/net/
  - name: tagger
    interval: 2m0s
    options: {}
  - name: temperature-ddwrt
    interval: 2m0s
    options:
      temperature-file: /proc/dmu/temperature
  - name: wl
    interval: 15s
    options:
      proc-net-wireless-path: /proc/net/wireless
      wl-exe: /usr/sbin/wl
