collectors:
  - name: datadog-client
  - name: dnsmasq-dhcp
  - name: dnsmasq-log
  - name: dnsmasq-queries
  - name: golang
  - name: load
  - name: memory
  - name: network-arp
  - name: network-conntrack
  - name: network-statistics
  - name: network-wireless
  - name: tagger
  - name: temperature-dd-wrt
  - name: uptime
  - name: wl
  - name: google-home
    options:
      ip: 192.168.3.98
  - name: google-home
    options:
      ip: 192.168.3.97
