collectors:
  - name: datadog-client
    interval: 2m0s
    options: {}
  - name: load
    interval: 30s
    options: {}
  - name: memory
    interval: 1m0s
    options:
      meminfo-file: /proc/meminfo
  - name: network-arp
    interval: 10s
    options:
      arp-file: /proc/self/net/arp
  - name: network-statistics
    interval: 10s
    options:
      device-path: /sys/class/net/
  - name: tagger
    interval: 2m0s
    options: {}
  - name: temperature-rpi
    interval: 2m0s
    options:
      temperature-file: /sys/class/thermal/thermal_zone0/temp
  - name: wireguard
    interval: 30s
    options:
      wg-exe: /usr/bin/wg
