collectors:
  - name: datadog-client
  - name: load
  - name: golang
  - name: memory
  - name: network-arp
  - name: network-statistics
  - name: tagger
  - name: temperature-rpi
  - name: uptime
  - name: wireguard
