collectors:
  - name: datadog-client
    interval: 2m0s
  - name: load
    interval: 30s
  - name: golang
    interval: 2m0s
  - name: memory
    interval: 1m0s
  - name: network-arp
    interval: 10s
    options:
      arp-file: /proc/self/net/arp
  - name: network-statistics
    interval: 10s
    options:
      sys-class-net-path: /sys/class/net/
  - name: tagger
    interval: 2m0s
  - name: temperature-rpi
    interval: 2m0s
    options:
      temperature-file: /sys/class/thermal/thermal_zone0/temp
  - name: uptime
    interval: 5m0s
  - name: wireguard
    interval: 30s
    options:
      wg-exe: /usr/bin/wg
